INSERT INTO rates(destination,prefix,cost) VALUES('Albania','355',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Albania Mobile Eagle','35567',0.4);
INSERT INTO rates(destination,prefix,cost) VALUES('Albania-Mobile','35568',0.41);
INSERT INTO rates(destination,prefix,cost) VALUES('Albania-Mobile Vodafone','35569',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Albania-Tirana','3554',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Algeria','213',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Algeria-Algiers','21321',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Algeria-Mobile','2136',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Algeria-Mobile Djezzy','21377',0.33);
INSERT INTO rates(destination,prefix,cost) VALUES('Algeria-Mobile Wataniya','2135',0.34);
INSERT INTO rates(destination,prefix,cost) VALUES('American Samoa','684',null);
INSERT INTO rates(destination,prefix,cost) VALUES('Andorra','376',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Andorra-Mobile','3763',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Angola','244',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Angola-Mobile','2449', 0.46);
INSERT INTO rates(destination,prefix,cost) VALUES('Anguilla','1264',0.23);
INSERT INTO rates(destination,prefix,cost) VALUES('Anguilla C&W Mobile','1264235',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Anguilla-Mobile','1264536',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Anguilla-Mobile Digicel','1264581',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Antigua','1268',0.23);
INSERT INTO rates(destination,prefix,cost) VALUES('Antigua C&W Mobile','1268464',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Antigua-Mobile','1268404', 0.34);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina','54',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Cellular-Domestic','541115', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Clave 1','54220', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Clave 2','542225', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Clave 3','542221', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Clave 4','542241', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Clave 5','542245', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Clave 6','542246', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Clave 7','542255', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina Toll-Free','54800', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Buenos Aires','5411',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Cordoba','54351',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Gral Pico','542302', 0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-La Pampa','542954',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-La Plata','54221',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Local Cities','54291',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Mar Del Plata','54223',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Mendoza','54261',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Mobile','549',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Moreno','542337', 0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Neuquen','54299',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Pergamino','542477', 0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-Rosario','54341',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-San Juan','54264',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Argentina-San Luis','542652', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Armenia','374',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Armenia-Mobile','3749',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Armenia-Yerevan','3741', 0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Aruba','297',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Aruba-Mobile','29756',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Ascension Island','247',0.6);
INSERT INTO rates(destination,prefix,cost) VALUES('Atlantic Ocean','871', 0.50);
INSERT INTO rates(destination,prefix,cost) VALUES('Atlantic West','874', 0.50);
INSERT INTO rates(destination,prefix,cost) VALUES('Australia','61',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Australia-Christmas Island','61891008', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Australia-Mobile','614', 0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Australia-Mobile-Satellite','611',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Australia-Sydney','6128',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria','43',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria Mobile Other','43651', 0.20);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria-Mobile A1','43664',0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria-Mobile Hutchinson','43660',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria-Mobile Mobile One','43699', 0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria-Mobile Tele2','436888', 0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria-Mobile Telering','43650',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria-Mobile Tmobile','43676',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Austria-Vienna','431',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Azerbaijan','994',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Azerbaijan-Baku','99412',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Bahamas','1242',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Bahamas-Mobile','1242357',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Bahrain','973',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Bahrain-Mobile','9733',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Bahrain-Mobile Zain','97336',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Bangladesh','880',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bangladesh-Chittagong','88031',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bangladesh-Dhaka','8802',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bangladesh-Mobile','8801',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bangladesh-Mobile Aktel','88018',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bangladesh-Mobile Grameen','88017',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bangladesh-Syhlet','880821',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Barbados','1246',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Barbados-C&W Mobile','124623',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Barbados-Mobile','124625', 3.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Barbados-Mobile Digicel','124626',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Belarus-Minsk','375172',0.36);
INSERT INTO rates(destination,prefix,cost) VALUES('Belarus-Mobile','37529',0.37);
INSERT INTO rates(destination,prefix,cost) VALUES('Belgium','32',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Belgium-Mobile','3248',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Belgium-Mobile Movistar','3249',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Belgium-Mobile Proximus','3247',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Belgium-Premium','3244', 0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Belize','501',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('Belize-Mobile','5016',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('Benin','229',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Benin-Mobile','2299', 2.98);
INSERT INTO rates(destination,prefix,cost) VALUES('Bermuda','1441',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bermuda-Mobile','14413',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Bhutan','975',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia','591',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia Cellular-Entel','59171',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia Mobile-Nuevatel','59170',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia Mobile-Telecel','59177',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia-Cochabamba','59144',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia-La Paz','59122',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia-Mobile','5917',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Bolivia-Santa Cruz','59133',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Bosnia And Herzegovina','387',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Bosnia And Herzegovina-Mobile','3876', 0.38);
INSERT INTO rates(destination,prefix,cost) VALUES('Botswana','267',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Botswana-Mobile','26771',0.23);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil','55',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-0800','55000800', 0.51);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Belem','5591', 0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Belo Horizonte','5531', 0.20);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Brasilia','5561', 0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Campinas','5519',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Curitiba','5541', 0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Fortaleza','5585', 0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Goiania','5562', 0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Governador Valadares','5533', 0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Mobile','55009', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Mobile (Telemar Pcs)','552286', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Mobile Oi','552186', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Porto Alegre','5551', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Recife','5581', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Rio De Janeiro','5521', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Salvador','5571', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Sao Jose Dos Campos','5512', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Sao Paulo','5511', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Sjc Local','55123009', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Brazil-Vitoria','5527',0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('British Virgin Islands','1284',0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('British Virgin Islands-C&W','1284540',0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('British Virgin Islands-Mobile','1284440',0.30);
INSERT INTO rates(destination,prefix,cost) VALUES('Brunei','673',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Brunei-Mobile','6738',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Bulgaria','359',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Bulgaria-Mobile','35989',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Bulgaria-Mobile Mobikom','35948', 0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Bulgaria-Mobile Mobitel','35988',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Bulgaria-On-Net','35932', 0.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Bulgaria-Sofia','3592',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Burkina Faso','226',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Burkina Faso Mobile','2267', 0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Burma(Myanmar)','95',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Burundi','257',0.70);
INSERT INTO rates(destination,prefix,cost) VALUES('Burundi-Mobile','25729',0.70);
INSERT INTO rates(destination,prefix,cost) VALUES('Cambodia','855',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Cambodia-Mobile','8551', 0.73);
INSERT INTO rates(destination,prefix,cost) VALUES('Cameroon','237',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Cameroon-Mobile Mtn','2377', 0.4);
INSERT INTO rates(destination,prefix,cost) VALUES('Cameroon-Mobile Orange','2379', 0.45);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada','1778',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada-1403','1403',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada-1416','1416',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada-1514','1514',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada-1604','1604',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada-1647','1647',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada-1905','1905',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Canada-Yukon','1867',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Cape Verde Islands','238',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Cape Verde Islands-Mobile','2389',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands','1345',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands-C&W Mobile','1345917',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands-Cayonef','1345626', 0.20);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands-Cayonem','1345229',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands-Digif','1345623',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands-Mobile','1345326',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands-Mobile Atw','1345514',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Cayman Islands-Mobile Digicel','1345325',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Central Africa Republic Mobile','2360', 0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Central Africa Republic Mobile','23670',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Central Africa Republic Mobile','23677',0.55);
INSERT INTO rates(destination,prefix,cost) VALUES('Central Africa Republic','23672',0.36);
INSERT INTO rates(destination,prefix,cost) VALUES('Central Africa Republic','23675',0.61);
INSERT INTO rates(destination,prefix,cost) VALUES('Central African Republic','236',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Chad','235',0.54);
INSERT INTO rates(destination,prefix,cost) VALUES('Chad Mobile','2352', 0.65);
INSERT INTO rates(destination,prefix,cost) VALUES('Chad Mobile-Celtel','2353', 0.65);
INSERT INTO rates(destination,prefix,cost) VALUES('Chile','56',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Chile-Mobile','569',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Chile-Santiago','562',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('China','86',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('China-Beijing','8610',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('China-Mobile','8613',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('China-Shanghai','8621',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia','57',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia Mobile-Movistar','57315',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia Mobile-Ola','57300',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Barranquilla','5753',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Bogota','5712',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Bucaramanga','57763',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Cali','5723',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Lex Telecom','5718230',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Medellin','5742',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Mobile','573',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Mobile-Comcel','57310',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Colombia-Pereira','57631',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Comoros','269',0.27);
INSERT INTO rates(destination,prefix,cost) VALUES('Comoros-Grand-Comore','2697', 0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Comoros-Mobile','2693',0.37);
INSERT INTO rates(destination,prefix,cost) VALUES('Congo','242',0.41);
INSERT INTO rates(destination,prefix,cost) VALUES('Congo Mobile Mtn','24206',0.37);
INSERT INTO rates(destination,prefix,cost) VALUES('Congo Mobile Warid','2424', 5.67);
INSERT INTO rates(destination,prefix,cost) VALUES('Congo Mobile-Zain','2425', 6.63);
INSERT INTO rates(destination,prefix,cost) VALUES('Cook Islands','682',0.66);
INSERT INTO rates(destination,prefix,cost) VALUES('Costa Rica','506',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Costa Rica-Mobile','5068',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Croatia','385',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Croatia-Mobile','38598',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Croatia-Mobile Vipnet','38591',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Cuba','53',0.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Cuba-Guantanamo Bay','5399',0.56);
INSERT INTO rates(destination,prefix,cost) VALUES('Cyprus','357',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Cyprus Special Services','357700',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Cyprus-Mobile','3579', 0.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Cyprus-Mobile Vodafone','35799',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Cyprus-Mobile-Mtn','35796',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Czech Republic','420',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Czech Republic-Mobile','42060', 2.57);
INSERT INTO rates(destination,prefix,cost) VALUES('Czech Republic-Prague','4202',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Dem Rep Congo (Zaire)','243',0.33);
INSERT INTO rates(destination,prefix,cost) VALUES('Dem Rep Congo (Zaire)-Mobile','24388', 2.76);
INSERT INTO rates(destination,prefix,cost) VALUES('Dem Rep Congo (Zaire)-Mobile Cct','24384',0.27);
INSERT INTO rates(destination,prefix,cost) VALUES('Dem Rep Congo (Zaire)-Mobile','24389',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Dem Rep Congo (Zaire)-Mobile','24381',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Dem Rep Congo','24397',0.27);
INSERT INTO rates(destination,prefix,cost) VALUES('Denmark','45',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Denmark-Mobile','452', 2.45);
INSERT INTO rates(destination,prefix,cost) VALUES('Denmark-Special-Services','4570', 10.76);
INSERT INTO rates(destination,prefix,cost) VALUES('Diego Garcia','246',0.7);
INSERT INTO rates(destination,prefix,cost) VALUES('Djibouti','253',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Dominica','1767',0.23);
INSERT INTO rates(destination,prefix,cost) VALUES('Dominica C&W Mobile','1767225',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Dominica Mobile','1767315',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Dominican Republic','1809',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Dominican Republic-Mobile','1809204',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('East Timor','670',0.37);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador','593',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador-Cuenca','593728',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador-Guayaquil','5934',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador-Mobile','5939',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador-Mobile Movistar','59398', 3.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador-Mobile Porta','593993', 3.57);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador-Mobile-Alegro','59396', 3.02);
INSERT INTO rates(destination,prefix,cost) VALUES('Ecuador-Quito','5932',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Egypt','20',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Egypt-Alexandria','203',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Egypt-Cairo','202',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Egypt-Mobile','2012',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador','503',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador Cell Telefonica','503710', 2.66);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador Cell-Digicel','50373',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador Cell-Personal','50370', 2.78);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador Cell-Telemovil','50372',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador','Cte', 55354211.00);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador-Mobile','5038',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('El Salvador-Telefonica','5032200',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Emsat-Thuraya','882',5.89);
INSERT INTO rates(destination,prefix,cost) VALUES('Equat. Guinea','240',0.42);
INSERT INTO rates(destination,prefix,cost) VALUES('Eritrea','291',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Estonia','372',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Estonia','Premium', 40997.00);
INSERT INTO rates(destination,prefix,cost) VALUES('Estonia-Mobile','3725', 6.23);
INSERT INTO rates(destination,prefix,cost) VALUES('Ethiopia','251',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Ethiopia Cellular-Addis Abeba','251911',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Ethiopia-Addis Ababa','25111',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Ethiopia-Mobile','2519',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Falkland Islands','500',0.56);
INSERT INTO rates(destination,prefix,cost) VALUES('Faroe Islands','298',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Fiji Islands','679',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('Finland','358',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Finland-Mobile','3584', 1.74);
INSERT INTO rates(destination,prefix,cost) VALUES('France','33',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('France Premium','338',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('France-Mobile','336', 1.72);
INSERT INTO rates(destination,prefix,cost) VALUES('France-Mobile Bouygues','33698',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('France-Mobile Orange','3367',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('France-Mobile Sfr','3361',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('France-Paris','331',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('French Guiana','594',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('French Guiana-Mobile','594694',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('French Polynesia','689',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Gabon Republic','241',0.42);
INSERT INTO rates(destination,prefix,cost) VALUES('Gabon Republic Mobile','2410', 6.58);
INSERT INTO rates(destination,prefix,cost) VALUES('Gabon Republic Mobile Zain','24107',0.39);
INSERT INTO rates(destination,prefix,cost) VALUES('Gambia','220',0.5);
INSERT INTO rates(destination,prefix,cost) VALUES('Georgia','995',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Georgia-Mobile','99577', 1.70);
INSERT INTO rates(destination,prefix,cost) VALUES('Georgia-Tbilisi','99532',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Germany','49',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Germany-Frankfurt','4969', 0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Germany-Hamburg','4940', 0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Germany-Mobile','4917', 2.02);
INSERT INTO rates(destination,prefix,cost) VALUES('Germany-Mobile Eplus','49155', 2.29);
INSERT INTO rates(destination,prefix,cost) VALUES('Ghana','233',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Ghana-Accra','233302',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Ghana-Mobile','23320',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Ghana-Mobile Millicom','23327',0.27);
INSERT INTO rates(destination,prefix,cost) VALUES('Ghana-Mobile-Mtn','23324',0.27);
INSERT INTO rates(destination,prefix,cost) VALUES('Gibraltar','350',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Gibraltar-Mobile','35054',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Greece','30',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Greece-Athens','3021',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Greece-Mobile','3069', 2.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Greece-Mobile Wind Hellas','30699',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Greenland','299',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Greenland-Mobile','2994',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Grenada','1473',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Grenada-C&W Mobile','1473403',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Grenada-Mobile','1473414',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Guadeloupe','590',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Guadeloupe-Mobile','590690',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Guam','1671',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Guatemala','502',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Guatemala - Telgua','5022220',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Guatemala-Cellular Pcs Sercom','5022223',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Guatemala-Cellular Telefonica','5022229', 2.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Guatemala-Mobile','5025',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Guatemala-Mobile-Comcel','502532',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Guinea','224',0.41);
INSERT INTO rates(destination,prefix,cost) VALUES('Guinea-Bissau','245',0.38);
INSERT INTO rates(destination,prefix,cost) VALUES('Guinea-Mobile','22465',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Guinea-Mobile Orange','22462',0.39);
INSERT INTO rates(destination,prefix,cost) VALUES('Guinea-Mobile Sotelgui','22460',0.45);
INSERT INTO rates(destination,prefix,cost) VALUES('Guinea-Mobile-Mtn','22464', 5.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Guyana','592',0.27);
INSERT INTO rates(destination,prefix,cost) VALUES('Guyana Mobile-Digicel','59266',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Guyana-Mobile','5926',0.27);
INSERT INTO rates(destination,prefix,cost) VALUES('Haiti','509',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Haiti-Mobile','5095', 3.91);
INSERT INTO rates(destination,prefix,cost) VALUES('Haiti-Mobile-Comcel','50939',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Haiti-Mobile-Digicel','5097',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Haiti-Port Au Prince','50921',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Honduras','504',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Honduras Mobile-Ctel','50495',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Honduras-Mobile','5049',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Honduras-Mobile Claro','504316', 2.42);
INSERT INTO rates(destination,prefix,cost) VALUES('Hong Kong','852',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Hong Kong-Mobile','8526',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Hungary','36',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Hungary-Budapest','361',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Hungary-Mobile','3620',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Iceland','354',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Iceland-Mobile','3546', 2.21);
INSERT INTO rates(destination,prefix,cost) VALUES('India','91',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Ahmadabad','9179',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Bangalore','9180',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Baroda (Vadodara)','91265',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Bombay (Mumbai)','9122',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Calcutta','9133',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Gujarat','9126', 0.29);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Hyderabad','9140',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Kerala','9147', 0.29);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Madras (Chennai)','9144',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Mobile','9198', 0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('India-Mobile-Bsnl','9194',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('India-New Delhi','9111',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia','62',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia Mobile Exelcom','62817',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia-Jakarta','6221',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia-Mobile','628',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia-Mobile Hutchison','62896',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia-Mobile Indosat','62815',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia-Mobile Telekomsel','62811',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Indonesia-Surabaya','6231',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Iran','98',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Iran-Mobile','989',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Iran-Tehran','9821',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Iraq','964',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Iraq-Baghdad','9641',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Iraq-Mobile','9647',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Iraq-Mobile Asiacell','96477',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Ireland','353',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Ireland Cellular-Vodafone','35387',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Ireland-Mobile','35385',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Iridium-Globalstar','881',1.36);
INSERT INTO rates(destination,prefix,cost) VALUES('Israel','972',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Israel-Jerusalem','9722', 0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Israel-Mobile','9725',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Israel-Pa','97222',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Israel-Pa Mobile','97259',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Israel-Tel Aviv','9723', 0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Italy','39',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Italy-Milan','3902',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Italy-Mobile','393', 3.67);
INSERT INTO rates(destination,prefix,cost) VALUES('Italy-Mobile Tim','3933',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Italy-Mobile Vodafone','3934',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Italy-Mobile Wind','3932',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Ivory Coast','225',0.34);
INSERT INTO rates(destination,prefix,cost) VALUES('Ivory Coast-Abidjan','2252',0.33);
INSERT INTO rates(destination,prefix,cost) VALUES('Ivory Coast-Cellular Comium','22566',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Ivory Coast-Cellular Orange','22507',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Ivory Coast-Cellular-Mtn','22504',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Ivory Coast-Mobile','2250', 3.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Jamaica','1876',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Jamaica-C&W Cellular','1876210',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Jamaica-Cellular-Digicell','187635',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Jamaica-Gotel','1876697', 1.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Jamaica-Mobile','1876301',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Japan','81',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Japan-Mobile','8170',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Japan-Osaka','816', 0.38);
INSERT INTO rates(destination,prefix,cost) VALUES('Japan-Tokyo','813',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Jordan','962',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Jordan-Amman','9626',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Jordan-Mobile','9627', 0.89);
INSERT INTO rates(destination,prefix,cost) VALUES('Jordan-Mobile Zain','96279',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan','731', 0.48);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Almaty','77272',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Almaty','77273',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Almaty','73272', 0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Astana','73172', 0.36);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Atyrau','73122', 0.83);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Karaganda','73212', 0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Mobile','7300', 1.54);
INSERT INTO rates(destination,prefix,cost) VALUES('Kazakhstan-Pavlodar','73182', 0.83);
INSERT INTO rates(destination,prefix,cost) VALUES('Kenya','254',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Kenya Mobile-Celtel','25473',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Kenya-Mobile','2547',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Kenya-Mobile Orange','254770', 1.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Kenya-Mobile Safaricom','25471',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Kenya-Nairobi','25420',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Kiribati','686',0.61);
INSERT INTO rates(destination,prefix,cost) VALUES('Kuwait','965',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Kuwait-Mobile','9656',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Kuwait-Mobile Vodafone','9659',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Kyrgyzstan','996',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Kyrgyzstan-Mobile','9965', 1.55);
INSERT INTO rates(destination,prefix,cost) VALUES('Laos','856',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Lebanon','961',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Lebanon-Mobile','9613',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Lesotho','266',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Liberia','231',0.42);
INSERT INTO rates(destination,prefix,cost) VALUES('Liberia Cellular-Cellcom','2317',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Liberia Cellular-Comium','2315',0.4);
INSERT INTO rates(destination,prefix,cost) VALUES('Liberia Cellular-Libercell','2314',0.38);
INSERT INTO rates(destination,prefix,cost) VALUES('Liberia Cellular-Libtelco','23212', 4.36);
INSERT INTO rates(destination,prefix,cost) VALUES('Liberia Cellular-Mtn','2316',0.38);
INSERT INTO rates(destination,prefix,cost) VALUES('Libya','218',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Libya-Mobile','2189',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Luxembourg','352',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Luxembourg Mobile','3526201', 4.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Macao','853',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Macedonia','389',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Macedonia-Mobile','3897', 4.97);
INSERT INTO rates(destination,prefix,cost) VALUES('Macedonia-Skopje','3892',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Malawi','265',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Malawi-Mobile','2654', 1.67);
INSERT INTO rates(destination,prefix,cost) VALUES('Malawi-Mobile Celtel','2655', 1.67);
INSERT INTO rates(destination,prefix,cost) VALUES('Malaysia','60',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Malaysia-Kuala Lumpur','603',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Malaysia-Mobile','601', 0.49);
INSERT INTO rates(destination,prefix,cost) VALUES('Maldives','960',0.72);
INSERT INTO rates(destination,prefix,cost) VALUES('Mali','223',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Mali-Bamako','223202', 3.05);
INSERT INTO rates(destination,prefix,cost) VALUES('Mali-Mobile Malitel','223630', 4.87);
INSERT INTO rates(destination,prefix,cost) VALUES('Mali-Mobile Orange','22370', 4.37);
INSERT INTO rates(destination,prefix,cost) VALUES('Malta','356',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Malta-Mobile','3569', 3.43);
INSERT INTO rates(destination,prefix,cost) VALUES('Marshall Islands','692',0.3);
INSERT INTO rates(destination,prefix,cost) VALUES('Martinique','596',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Martinique-Mobile','596696',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Mauritania','222',0.41);
INSERT INTO rates(destination,prefix,cost) VALUES('Mauritius','230',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Mauritius Mobile','23025', 0.75);
INSERT INTO rates(destination,prefix,cost) VALUES('Mauritius Rodriguez','2308', 0.75);
INSERT INTO rates(destination,prefix,cost) VALUES('Mayotte','26976',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico','52',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico Ea 1','52834',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico Ea 2','52475',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico Ea 3','52626',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Guadalajara-Mobile','52133',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Gudalajara','52333', 0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Gudalajara 5233','5233',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Mexico City','52555', 0.20);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Mexico City 5255','5255',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Mexico City-Mobile','52155',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Mobile','521',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Monterrey','52818', 0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Monterrey 5281','5281',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Monterrey-Mobile','52181', 0.82);
INSERT INTO rates(destination,prefix,cost) VALUES('Mexico-Puebla','52222',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Micronesia','691',0.39);
INSERT INTO rates(destination,prefix,cost) VALUES('Moldova','373',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('Moldova-Chisinau','3732', 2.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Moldova-Mobile','37369',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Moldova-Pridnestrovie','3735',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Monaco','377',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Monaco-Mobile','3776',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Monaco-Mobile Kfor','3774',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Mongolia','976',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Montenegro','382',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Montenegro Cellular','38267',0.37);
INSERT INTO rates(destination,prefix,cost) VALUES('Montserrat','1664',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Montserrat-Mobile','166410', 2.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Morocco','212',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Morocco Cellular Maroc','212610',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Morocco Cellular Meditel','212612',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Morocco-Casablanca','212522',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Morocco-Marco','212539',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Morocco-Mobile','2126', 4.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Morocco-Rabat','212537',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Mozambique','258',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Mozambique-Mobile','2588',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Mozambique-Mobile Vodacom','25884',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Mozambique-Mobile-Mcel','25882',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Namibia','264',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Namibia-Mobile','26481',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Nepal','977',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Nepal-Kathmandu','9771', 0.69);
INSERT INTO rates(destination,prefix,cost) VALUES('Nepal-Mobile','97798',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Nepal-Mobile Spice','977980',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Netherlands','31',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Netherlands Antilles','599',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Netherlands Antilles-Mobile','59951', 1.85);
INSERT INTO rates(destination,prefix,cost) VALUES('Netherlands Special Services','319', 10.76);
INSERT INTO rates(destination,prefix,cost) VALUES('Netherlands','Rotterdam', 3421.00);
INSERT INTO rates(destination,prefix,cost) VALUES('Netherlands-Amsterdam','3120',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Netherlands-Mobile','316', 2.55);
INSERT INTO rates(destination,prefix,cost) VALUES('New Caledonia','687',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('New Zealand','64',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('New Zealand-Mobile','642', 3.56);
INSERT INTO rates(destination,prefix,cost) VALUES('Nicaragua','505',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Nicaragua Mobile Claro','50533', 3.87);
INSERT INTO rates(destination,prefix,cost) VALUES('Nicaragua-Mobile','5058',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Niger','227',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('Niger Cellular-Moov','22794',0.35);
INSERT INTO rates(destination,prefix,cost) VALUES('Niger Cellular-Sahelcom','22793',0.37);
INSERT INTO rates(destination,prefix,cost) VALUES('Niger Cellular-Zain','22796',0.33);
INSERT INTO rates(destination,prefix,cost) VALUES('Niger Mobile','2279', 2.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Niger Mobile-Orange','22790',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria','234',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Abuja','2349', 1.51);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Benin','23452', 2.04);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Lagos','2341', 1.54);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Lagos Ld','234177', 1.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Mobile','23490',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Mobile-Globacom','234805',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Mobile-Mtn','234803',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Mobile-Vee','234802',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Moble Nitel','234804',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Onitsha','23446', 1.55);
INSERT INTO rates(destination,prefix,cost) VALUES('Nigeria-Port Hardcort','23484', 1.50);
INSERT INTO rates(destination,prefix,cost) VALUES('Niue','683',0.57);
INSERT INTO rates(destination,prefix,cost) VALUES('Norfolk Islands','6723',0.66);
INSERT INTO rates(destination,prefix,cost) VALUES('North Korea','850',0.46);
INSERT INTO rates(destination,prefix,cost) VALUES('Northern Mariana Islands','1670',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Norway','47',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Norway Special Services','4702',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Norway-Mobile','474',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Oman','968',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Oman-Mobile','9689',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Outbound On-Net To Directory','*2007', 10.50);
INSERT INTO rates(destination,prefix,cost) VALUES('Pacific Ocean','872', 26.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Pakistan','92',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Pakistan','Cellular-Mobilink', 10153.00);
INSERT INTO rates(destination,prefix,cost) VALUES('Pakistan-Islamabad','9251',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Pakistan-Karachi','9221',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Pakistan-Lahore','9242',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Pakistan-Mobile','923',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Palau','680',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Palestinian Authority','970',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Palestinian Authority-Mobile','97059',0.23);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama','507',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Aguadulce','507986', 0.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Changuinola','5077581', 0.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Chitre','5079772', 0.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Colon','5074', 0.56);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-David City','507721', 0.73);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Las Tablas','5079944', 0.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Mobile','5076', 2.36);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Mobile C&W','507650',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Panama City','5072',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Panama City 5075','5075',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Panama-Santiago','5079390', 0.59);
INSERT INTO rates(destination,prefix,cost) VALUES('Papau New Guinea','675',0.47);
INSERT INTO rates(destination,prefix,cost) VALUES('Paraguay','595',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Paraguay-Asuncion','59521',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Paraguay-Mobile','595220', 0.94);
INSERT INTO rates(destination,prefix,cost) VALUES('Paraguay-Mobile-Tigo','59598',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru','51',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru Mobile-Claro','519730',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru Mobile-Telefonica','511951', 2.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru','Lima 5116', 5627.60);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru-Arequipa','5154',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru-Lima','511',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru-Mobile','51419', 2.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru-Rural','515281', 1.82);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru-Rural 2','514181', 1.82);
INSERT INTO rates(destination,prefix,cost) VALUES('Peru-Trujillo','5144',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Philippines','63',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Philippines-Manila','632',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Philippines-Mobile','639',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Philippines-Mobile Globe','63905',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Poland','48',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Poland-Mobile','4850',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Poland-Warsaw','4822',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Portugal','351',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Portugal-Lisbon','35121',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Portugal-Mobile','3519', 1.98);
INSERT INTO rates(destination,prefix,cost) VALUES('Puerto Rico','1787',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Qatar','974',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Qatar-Cellular','9742',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Reunion Island','262',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Reunion Island','Mayotte', 288495.90);
INSERT INTO rates(destination,prefix,cost) VALUES('Reunion Island','Mayotte-Mobile', 288902.90);
INSERT INTO rates(destination,prefix,cost) VALUES('Reunion Island-Mobile','262692',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania','40',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania-Bucharest','4021',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania-Mobile','407', 0.83);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania-Mobile Cosmorom','4076',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania-Mobile Orange','4075',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania-Mobile Orange','4074',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania-Mobile Telemobil','4078', 0.83);
INSERT INTO rates(destination,prefix,cost) VALUES('Romania-Mobile Vodafone','4072',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia','7',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia','Globaltel Satellite', 8749.40);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia','Outer St. Petersburg', 85938.60);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-1','7336',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-2','73012',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-3','7424',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-3- 7281','7281', 0.50);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-Mobile','79', 0.81);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-Moscow','7495',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-Moscow Suburb','7096', 0.28);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-Rostovdon','78632', 0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Russia-St. Petersburg','7812',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Rwanda','250',0.33);
INSERT INTO rates(destination,prefix,cost) VALUES('Rwanda-Mobile','25005',0.32);
INSERT INTO rates(destination,prefix,cost) VALUES('San Marino','378',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Saudi Arabia','966',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Saudi Arabia-Dhahran','9663', 1.54);
INSERT INTO rates(destination,prefix,cost) VALUES('Saudi Arabia-Jeddah','96622',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Saudi Arabia-Jeddah Mecca','96625', 0.49);
INSERT INTO rates(destination,prefix,cost) VALUES('Saudi Arabia-Mobile','9665',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Saudi Arabia-Riyadh','96612',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Senegal Republic','221',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Senegal Republic Mobile Orange','22177',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Senegal Republic-Cell Tigo','22176',0.34);
INSERT INTO rates(destination,prefix,cost) VALUES('Senegal Republic-Dakar','2218', 6.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Senegal Republic-Mobile','2216', 6.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Serbia','381',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Serbia-Belgrade','38111',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Serbia-Mobile','3816',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Serbia-Mobile Mobtel','38163',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Serbia-Mobile Mts','38164',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Serbia-Montenegro','3818', 1.04);
INSERT INTO rates(destination,prefix,cost) VALUES('Seychelles Islands','248',0.62);
INSERT INTO rates(destination,prefix,cost) VALUES('Singapore','65',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Singapore-Mobile','659',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Slovakia','421',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Slovakia-Mobile','4219',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Slovenia','386',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Slovenia-Mobile','38640',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('South Africa','27',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('South Africa Value Added Network', '2710001',0.126 );
INSERT INTO rates(destination,prefix,cost) VALUES('South Africa-Cell Other','27811',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('South Africa-Cellular-Cell C','2774',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('South Africa-Cellular-Mtn','2773',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('South Africa-Cellular-Vodacom','27711',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('South Africa-Johannesburg','2711', 0.51);
INSERT INTO rates(destination,prefix,cost) VALUES('South Korea','82',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('South Korea-Mobile','821',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('South Korea-Seoul','822',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('South Sudan','211',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Spain','34',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Spain Cellular-Telefonica','34699',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Spain-Barcelona','3493', 0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Spain-Madrid','3491', 0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Spain-Mobile','346',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Spain-Special','341248', 10.76);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka','94',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka Colombo Slt', '10352', 3.20);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka Slt', '10363',3.20);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka-Colombo','941', 2.02);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka-Mobile Celltel','9472',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka-Mobile Dialog','9477',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka-Mobile Hutchinson','9478',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Sri Lanka-Mobile Mobi Tel','9471',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Kitts','1869',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Kitts-C&W Mobile','1869662',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Kitts-Mobile','1869556',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Lucia','1758',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Lucia-C&W Mobile','1758284',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Lucia-Mobile','1758518',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Pierre & Miquelon','508',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Vincent','1784',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Vincent-C&W Mobile','1784454',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('St. Vincent-Mobile','1784430',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Sudan','249',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Sudan Cellular-Areeba','24992',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Sudan Cellular-Kabartel','24915',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Sudan Cellular-Sudatel','24912',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Sudan Cellular-Vivacel','24995',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Sudan Mobile','2499', 2.02);
INSERT INTO rates(destination,prefix,cost) VALUES('Suriname','597',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Suriname-Mobile','5978',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Swaziland','268',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Swaziland-Mobile','26860', 2.84);
INSERT INTO rates(destination,prefix,cost) VALUES('Sweden','46',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Sweden-Mobile','4610',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Sweden-Stockholm','468',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Switzerland','41',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Switzerland-Celluar Swisscom','41774', 3.47);
INSERT INTO rates(destination,prefix,cost) VALUES('Switzerland-Cellular Orange','4178',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Switzerland-Cellular Sunrise','4176',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Switzerland-Mobile','417', 3.10);
INSERT INTO rates(destination,prefix,cost) VALUES('Syria','963',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Syria-Mobile','9639',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Taiwan','886',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Taiwan-Mobile','8869', 1.41);
INSERT INTO rates(destination,prefix,cost) VALUES('Taiwan-Taipei','8862', 0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Tajikistan','992',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Tajikistan-Dushanbe','992372',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Tajikistan-Mobile','9929',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Tanzania','255',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Tanzania-Dar Es Salaam','25522',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Tanzania-Mobile','25574',0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Thailand','66',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Thailand-Bangkok','662',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Thailand-Mobile','668', 0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Togo','228',0.3);
INSERT INTO rates(destination,prefix,cost) VALUES('Togo Mobile-Togocel','22806', 6.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Togo-Mobile','2289',0.31);
INSERT INTO rates(destination,prefix,cost) VALUES('Tokelau','690',0.66);
INSERT INTO rates(destination,prefix,cost) VALUES('Tonga Islands','676',0.56);
INSERT INTO rates(destination,prefix,cost) VALUES('Trinidad','1868',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Trinidad Cellular-Other','186835',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Trinidad Tstt Cellular','186846',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Trinidad Tstt Cellular 186868','186868',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Tunisia','216',0.58);
INSERT INTO rates(destination,prefix,cost) VALUES('Tunisia-Mobile','2169',0.45);
INSERT INTO rates(destination,prefix,cost) VALUES('Tunisia-Mobile-Tunisiana','2162',0.48);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey','90',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey Mobile-Vodafone Northern','905428', 1.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Adana','90322',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Ankara','90312',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Antalya','90242',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Istanbul','90212',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Izmir','90232',0.07);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Mobile','905',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Mobile Aria','9055',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Mobile Ay','9050', 1.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Mobile Turkcell','9053',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-Mobile Vodafone','9054', 0.77);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkey-North Cyprus','90392',0.08);
INSERT INTO rates(destination,prefix,cost) VALUES('Turkmenistan','993',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Turks & Caicos','1649',0.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Turks & Caicos C&W Cellular','1649231',0.25);
INSERT INTO rates(destination,prefix,cost) VALUES('Turks & Caicos Cellular','1649331',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Tuvalu','688',0.66);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda','256',0.34);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda Mobile Celtel','25675',0.15);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda Mobile-Gemtel','256477',0.26);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda Mobile-Itel Telecom','256760', 1.94);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda Mobile-Mtn','25639',0.23);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda Mobile-Orange','25679',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda Mobile-Utl','25671',0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Uganda Mobile-Warid','25670',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine','380',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine Mobile Astelit','38063',0.21);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine Mobile Kievstar','38067',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine Mobile Mts','38050',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Dnipropetrovsk','380562', 1.55);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Kiev','38045', 1.47);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Krivoi Rog','380564', 1.55);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Lviv','380322', 1.55);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Mobile','38068',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Odessa','38048', 1.54);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Sevastopol','380692', 1.57);
INSERT INTO rates(destination,prefix,cost) VALUES('Ukraine-Simferolpol','380652', 1.57);
INSERT INTO rates(destination,prefix,cost) VALUES('United Arab Emirates','971',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('United Arab Emirates-Mobile','97150',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom','44',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom Special Services','448',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-London','44207', 0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-Mobile','447', 4.73);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-Mobile Pns','4470', 9.86);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-Mobile-H3g','447723',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-Mobile-O2','447701',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-Mobile-Orange','447773',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-Mobile-Tmobile','447903',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('United Kingdom-Mobile-Vodafone','447721',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Uruguay','598',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Uruguay-Mobile','5989',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Uruguay-Montevideo','5982',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Us (Estados Unidos)','1',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Us Tollfree','1800',0.05);
INSERT INTO rates(destination,prefix,cost) VALUES('Us Virgin Islands','1340',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Us-Ak-907 (Alaska)','1907',0.1);
INSERT INTO rates(destination,prefix,cost) VALUES('Us-C+W Toll Free','1800744', 0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Us-Hi-808 (Hawaii)','1808',0.16);
INSERT INTO rates(destination,prefix,cost) VALUES('Us-Nyc','1212', 0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Us-Texas','1210', 0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Usa-Nj-201 Ad','*221201', 0.18);
INSERT INTO rates(destination,prefix,cost) VALUES('Uzbekistan','998',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Uzbekistan-Mobile','9989', 1.22);
INSERT INTO rates(destination,prefix,cost) VALUES('Vanuatu Republic','678',0.66);
INSERT INTO rates(destination,prefix,cost) VALUES('Venezuela','58',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Venezuela Mobile Telcel','58414',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Venezuela-Caracas','58212',0.06);
INSERT INTO rates(destination,prefix,cost) VALUES('Venezuela-Mobile','58418', 1.71);
INSERT INTO rates(destination,prefix,cost) VALUES('Venezuela-Mobile Tim Digitel','58412',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Venezuela-Mobile-Movilnet','58416',0.09);
INSERT INTO rates(destination,prefix,cost) VALUES('Venezuela-Valencia','58241', 0.24);
INSERT INTO rates(destination,prefix,cost) VALUES('Vietnam','84',0.11);
INSERT INTO rates(destination,prefix,cost) VALUES('Vietnam-Mobile','849',0.12);
INSERT INTO rates(destination,prefix,cost) VALUES('Wallis & Futuna','681',0.33);
INSERT INTO rates(destination,prefix,cost) VALUES('Western Samoa','685',0.66);
INSERT INTO rates(destination,prefix,cost) VALUES('Yemen','967',0.19);
INSERT INTO rates(destination,prefix,cost) VALUES('Yemen-Mobile','96771',0.17);
INSERT INTO rates(destination,prefix,cost) VALUES('Zambia','260',0.13);
INSERT INTO rates(destination,prefix,cost) VALUES('Zambia-Mobile','26095',0.2);
INSERT INTO rates(destination,prefix,cost) VALUES('Zimbabwe','263',0.14);
INSERT INTO rates(destination,prefix,cost) VALUES('Zimbabwe Mobil-Telecel','26323', 3.53);
INSERT INTO rates(destination,prefix,cost) VALUES('Zimbabwe-Mobile Econet','26377',0.33);
INSERT INTO rates(destination,prefix,cost) VALUES('Zimbabwe-Mobile Netone','26311', 3.53);
